#!/usr/bin/env php
<?php

require 'pearfarm.php';

if (isset($argv[1]))
{
    $specfile = $argv[1];
}
else
{
    $specfile = getcwd() . '/pearfarm.spec';
}

print "Reading specfile at {$specfile}...\n";
if (!file_exists($specfile))
{
    print "{$specfile} is not a pearfarm.spec file.\n";
    exit(1);
}

include $specfile;
if (!isset($spec))
{
    print "specfile didn't create a local variable named '\$spec'.";
    exit(1);
}

print_r($spec);

$spec->writePackageFile();
