#!/usr/bin/env php
<?php

if (strpos('@php_bin@', '@php_bin') === 0) {  // not a pear install
    $prefix = dirname(__FILE__);
    define('PEARFARM_CMD', 'php pearfarm');
} else {
    $prefix = 'pearfarm';
    define('PEARFARM_CMD', 'pearfarm');
}

function Pearfarm_Autoloader($class) {
  // set class file name
  $file = str_replace('_', '/', str_replace('\\', '/', $class)) . '.php';
  
  // checks all the include paths to see if the file exist
  $paths = explode(PATH_SEPARATOR, get_include_path());
  foreach ($paths as $path) {
    if (file_exists($path . '/' . $file)) {
      require $path . '/' . $file;
      return true;
    }
  }
}

spl_autoload_register('Pearfarm_Autoloader');

set_include_path(
  dirname(__FILE__) . '/src/' . PATH_SEPARATOR .
  get_include_path()
);

$cli = new Pearfarm_CLIController($argv);
$cli->register(new Pearfarm_Task_Plant());
$cli->register(new Pearfarm_Task_Collect());
$cli->register(new Pearfarm_Task_Try());
$cli->register(new Pearfarm_Task_Deliver());
$cli->register(new Pearfarm_Task_Init());
$cli->run();
exit(0);
